### ISSUE TITLE
Fix handling of errors when encoding exceptions with scodec

### ISSUE THREAD

**Issue by travisbrown** [finagle/finagle-serial#17]
Currently any errors that happen while Scodec is encoding request or response types are correctly wrapped in `CodecError` (not `ServerApplicationError`), but if encoding fails while encoding an exception, you'll get the `CodecError` string wrapped in a `ServerApplicationError`.

This isn't a terribly big deal, since exceptions should be easy to encode and shouldn't usually fail, but it wouldn't be too hard to fix.

**Comment by travisbrown** [comment]
Just to clarify: this is only a problem if an error happens while encoding `CodecError` or `ApplicationError`.

**Comment by travisbrown** [comment]
Looking back at this after a few weeks, I think I'm fine with the current behavior, and at least in the case of `CodecError` it's the most straightforward approach to avoiding a loop where you fail while encoding a `CodecError`, and then while encoding the `CodecError` that represents that failure, and so on.

As I mention above, failure encoding one of these two error types should be extremely rare (like the case of an Scodec error message being more than 65,536 characters long), so it doesn't seem unreasonable to use `ServerApplicationError` as a "we give up, something really bad happened" error.

Mind if I close this, @vkostyukov?

**Comment by vkostyukov** [comment]
Totally agree! Please go ahead with closing it.
